<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<AssemblyVersion>1.0.0.0</AssemblyVersion>
	<FileVersion>1.0.0.0</FileVersion>
	<VersionPrefix>1.0.0.0</VersionPrefix>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<Title>CodedThought.Core.Data.OleDb</Title>
	<Authors>Erik Bartlow</Authors>
	<Company>Erik Bartlow</Company>
	<Description>The CodedThought.Core.Data.OleDb package is a custom database provider for use with OleDb Compatible Server.</Description>
	<PackageProjectUrl>https://github.com/erikbartlow/CodedThought.Core</PackageProjectUrl>
	<RepositoryType>git</RepositoryType>
	<RepositoryUrl>https://github.com/erikbartlow/CodedThought.Core</RepositoryUrl>
	<IncludeContentInPack>true</IncludeContentInPack>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<IncludeReferencedProjects>true</IncludeReferencedProjects>
	<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<Copyright>Copyright (c) 2024, Erik Bartlow, All Rights Reserved</Copyright>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
	<PackageReference Include="System.Data.OleDb" Version="8.0.0" />
  </ItemGroup>

  <Choose>
	<When Condition="'$(Configuration)' == 'Release'">
	  <ItemGroup>
		<PackageReference Include="CodedThought.Core" Version="8.0.1.6" />
		<PackageReference Include="CodedThought.Core.Configuration" Version="8.0.1" />
	  </ItemGroup>
	</When>
  </Choose>

  <Choose>
	<When Condition="'$(Configuration)' == 'Debug'">
	  <ItemGroup>
		<ProjectReference Include="..\CodedThought.Core\CodedThought.Core.Configuration\CodedThought.Core.Configuration.csproj" />
	  </ItemGroup>
	</When>
  </Choose>


  <ItemGroup>
	<None Update="LICENSE" Pack="true" PackagePath="" />
	<None Update="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
